// This file will now export a single, sorted array of all portfolio images.

export const portfolioImages = [
  "/portfolio-optimized/p01.webp",
  "/portfolio-optimized/p02.webp",
  "/portfolio-optimized/p03.webp",
  "/portfolio-optimized/p04.webp",
  "/portfolio-optimized/p05.webp",
  "/portfolio-optimized/p06.webp",
  "/portfolio-optimized/p07.webp",
  "/portfolio-optimized/p08.webp",
  "/portfolio-optimized/p09.webp",
  "/portfolio-optimized/p10.webp",
  "/portfolio-optimized/p11.webp",
  "/portfolio-optimized/p12.webp",
  "/portfolio-optimized/p13.webp",
  "/portfolio-optimized/p14.webp",
  "/portfolio-optimized/p15.webp",
  "/portfolio-optimized/p16.webp",
  "/portfolio-optimized/p17.webp",
  "/portfolio-optimized/p18.webp",
  "/portfolio-optimized/p19.webp",
  "/portfolio-optimized/p20.webp",
  "/portfolio-optimized/p21.webp",
  "/portfolio-optimized/p22.webp",
  "/portfolio-optimized/p23.webp",
  "/portfolio-optimized/p24.webp",
  "/portfolio-optimized/p25.webp",
  "/portfolio-optimized/p26.webp",
  "/portfolio-optimized/p27.webp",
  "/portfolio-optimized/p28.webp",
  "/portfolio-optimized/p29.webp",
  "/portfolio-optimized/p30.webp",
  "/portfolio-optimized/p31.webp",
]; 